//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunFirstAPI_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class API_Hit
    {
        public int id { get; set; }
        public string API { get; set; }
        public Nullable<int> Hit { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
    }
}
