//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunFirstAPI_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Brand_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Brand_tbl()
        {
            this.Franchise_tbl = new HashSet<Franchise_tbl>();
        }
    
        public int br_id { get; set; }
        public string br_name { get; set; }
        public string br_creaetedby { get; set; }
        public Nullable<System.DateTime> br_createdat { get; set; }
        public string br_updatedby { get; set; }
        public Nullable<System.DateTime> br_updatedat { get; set; }
        public string br_isdeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Franchise_tbl> Franchise_tbl { get; set; }
    }
}
