//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunFirstAPI_Pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchise_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Franchise_tbl()
        {
            this.Requirement_data = new HashSet<Requirement_data>();
        }
    
        public int fr_id { get; set; }
        public Nullable<int> fr_Placement_Officer_id { get; set; }
        public Nullable<System.DateTime> fr_visit_date { get; set; }
        public string fr_type { get; set; }
        public string fr_name { get; set; }
        public Nullable<int> fr_br_id { get; set; }
        public int fr_pr_id { get; set; }
        public string fr_owner_mgr { get; set; }
        public string fr_mobile { get; set; }
        public string fr_landline { get; set; }
        public string fr_emial { get; set; }
        public string fr_address { get; set; }
        public Nullable<int> fr_pincode { get; set; }
        public string fr_area { get; set; }
        public string fr_city { get; set; }
        public string fr_district { get; set; }
        public string fr_state { get; set; }
        public string fr_location_lat { get; set; }
        public string fr_Location_lng { get; set; }
        public Nullable<int> fr_req_jan { get; set; }
        public Nullable<int> fr_req_feb { get; set; }
        public Nullable<int> fr_req_mar { get; set; }
        public Nullable<int> fr_req_apr { get; set; }
        public Nullable<int> fr_req_may { get; set; }
        public Nullable<int> fr_req_jun { get; set; }
        public Nullable<int> fr_req_jul { get; set; }
        public Nullable<int> fr_req_aug { get; set; }
        public Nullable<int> fr_req_sept { get; set; }
        public Nullable<int> fr_req_oct { get; set; }
        public Nullable<int> fr_req_nov { get; set; }
        public Nullable<int> fr_req_dec { get; set; }
        public Nullable<decimal> fr_sal_range_fresher { get; set; }
        public string fr_contact_person { get; set; }
        public string fr_contact { get; set; }
        public string fr_ceatedby { get; set; }
        public Nullable<System.DateTime> fr_createdat { get; set; }
        public string fr_updateby { get; set; }
        public Nullable<System.DateTime> fr_updatedat { get; set; }
        public string fr_isdeleted { get; set; }
        public string fr_Officer_email { get; set; }
        public Nullable<int> fr_no_tech_work { get; set; }
    
        public virtual Brand_tbl Brand_tbl { get; set; }
        public virtual Product_tbl Product_tbl { get; set; }
        public virtual User_tbl User_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirement_data> Requirement_data { get; set; }
    }
}
