//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunFirstAPI_Pro.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_tbl()
        {
            this.Franchise_tbl = new HashSet<Franchise_tbl>();
            this.Requirement_data = new HashSet<Requirement_data>();
        }
    
        public int id { get; set; }
        [DisplayName("Firstname")]
        [Required(ErrorMessage = "Enter Firstname")]
        [DataType(DataType.Text)]
        public string ur_firstname { get; set; }
        [DisplayName("Lastname")]
        [Required(ErrorMessage = "Enter Lastname")]
        [DataType(DataType.Text)]
        public string ur_lastname { get; set; }
        [DisplayName("Email ID")]
        [Required(ErrorMessage = "Enter Email ID")]
        [DataType(DataType.EmailAddress)]
        public string ur_email { get; set; }
        [DisplayName("Mobile")]
        [Required(ErrorMessage = "Enter Mobile Number")]
        [DataType(DataType.PhoneNumber)]
        public string ur_mobile { get; set; }
        [DisplayName("Entity")]
        [Required(ErrorMessage = "Enter Entity")]
        [DataType(DataType.Text)]
        public string ur_entity { get; set; }
        [DisplayName("Password")]
        [Required(ErrorMessage = "Enter Password")]
        [DataType(DataType.Password)]
        public string ur_password { get; set; }
        [DisplayName("Created By")]
        [DataType(DataType.Text)]
        public string ur_createdby { get; set; }
        [DisplayName("Date")]
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> ur_createdat { get; set; }
        public string ur_updateby { get; set; }
        public Nullable<System.DateTime> ur_updatedat { get; set; }
        public string ur_isdeleted { get; set; }
        [DisplayName("Role")]
        [Required(ErrorMessage = "Enter Role")]
        [DataType(DataType.Text)]
        public string ur_role { get; set; }
        [DisplayName("Designation")]
        [Required(ErrorMessage = "Enter Designation")]
        [DataType(DataType.Text)]
        public string ur_desg { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Franchise_tbl> Franchise_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requirement_data> Requirement_data { get; set; }
    }
}
